export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_ERROR = "LOGIN_REQUEST_ERROR";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_REQUEST_SUCCESS = "SIGNUP_REQUEST_SUCCESS";
export const SIGNUP_REQUEST_ERROR = "SIGNUP_REQUEST_ERROR";

export const CREATE_ROOM_REQUEST = "CREATE_ROOM_REQUEST";
export const CREATE_ROOM_SUCCESS = "CREATE_ROOM_SUCCESS";
export const CREATE_ROOM_FAILURE = "CREATE_ROOM_FAILURE";

export const LIST_ROOMS_SUCCESS = "LIST_ROOMS_SUCCESS";
export const LIST_ROOMS_REQUEST = "LIST_ROOMS_REQUEST";
export const LIST_ROOMS_FAILURE = "LIST_ROOMS_FAILURE";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";

export const REQUEST_CHAT_MESSAGES = "REQUEST_CHAT_MESSAGES";
export const REQUEST_CHAT_MESSAGES_SUCCESS = "REQUEST_CHAT_MESSAGES_SUCCESS";
export const REQUEST_CHAT_MESSAGES_FAILURE = "REQUEST_CHAT_MESSAGES_FAILURE";

export const SEND_CHAT_MESSAGE_REQUEST = "SEND_CHAT_MESSAGE_REQUEST";
export const SEND_CHAT_MESSAGE_REQUEST_SUCCESS = "SEND_CHAT_MESSAGE_REQUEST_SUCCESS";
export const SEND_CHAT_MESSAGE_REQUEST_ERROR = "SEND_CHAT_MESSAGE_REQUEST_ERROR";

export const SEND_MAIL_REQUEST = "SEND_MAIL_REQUEST";
export const SEND_MAIL_REQUEST_SUCCESS = "SEND_MAIL_REQUEST_SUCCESS";
export const SEND_MAIL_REQUEST_ERROR = "SEND_MAIL_REQUEST_ERROR";

export const LIST_FILES_REQUEST = "LIST_FILES_REQUEST";
export const LIST_FILES_REQUEST_SUCCESS = "LIST_FILES_REQUEST_SUCCESS";
export const LIST_FILES_REQUEST_ERROR = "LIST_FILES_REQUEST_ERROR";
